name: Enhancement
description: Request for new features
labels: ['T: Suggestion']

body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        If applicable, add screenshots or mockups to help explain your request.
    validations:
      required: true